#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP Console
// +----------------------------------------------------------------------

namespace think;

require __DIR__ . '/vendor/autoload.php';

// 执行命令行应用
Console::init();
